# Set port for config server peer2.
server:
  port: 8889

# Register self as a client to discovery server peer1 and peer2.
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
